[package]
name = "spring-web"
description = "rust microservice framework"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
spring-boot = { path = "../spring-boot", version = "0.0.8" }
axum = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["full"] }
byte-unit = { workspace = true, features = ["serde"] }
schemars = { workspace = true }
inventory = { workspace = true }
axum-server = { workspace = true, optional = true }
instant-acme = { workspace = true, optional = true }
rcgen = { workspace = true, optional = true }

[features]
tls = ["axum-server", "axum-server/tls-rustls", "instant-acme", "rcgen"]
