[package]
name = "opentelemetry-example"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
spring = { path = "../../spring" }
spring-web = { path = "../../spring-web" }
spring-sqlx = { path = "../../spring-sqlx", features = ["postgres"] }
spring-opentelemetry = { path = "../../spring-opentelemetry", features = [
    "grpc",
] }
tokio = { workspace = true }
anyhow = { workspace = true }
