name: Publish

on:
  workflow_dispatch:
    inputs:
      msg:
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependency
        run: cargo install cargo-workspaces && apt-get install protobuf-compiler
      - name: Build
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --workspace --verbose
      - name: Run Publish
        run: |
          sed -i 's/"examples.*,//' Cargo.toml &&
          cp README.md ./spring/ &&
          sed -i 's|include_str!("../../README.md")|include_str!("../README.md")|' spring/src/lib.rs
          cargo ws publish --publish-as-is --token=${{secrets.CARGO_TOKEN}} --allow-dirty
